# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artiste',
            new_name='artist',
        ),
    ]
